os:
  - linux
  - osx
language: node_js
node_js:
  - "4"
  - "6"
before_script:
  - cp test/patch-virtual-serialport/index.js node_modules/virtual-serialport/index.js
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: d99df312a727b3837593be2fe36c298d0322b3641f3cba7141c511f40e6c63f7
